name: Build Common

on:  
    push:
        branches-ignore:
            - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.200 
    - name: Test
      run: dotnet test ./DotNet/ssndk.sln --configuration Release 